id: P2CA048CE
initial_creation_type: input
source_metadata:
  title: Chatral Rinpoche
  language: en
  description: 'Texts by and about the great Dzogchen master Chatral Sangye Dorje
    (bya bral sangs rgyas rdo rje, 1913–2015):'
  volume:
    fbb34aab010b41d8a78548619a6d90f0:
      title: Spontaneous Advice Connected with a Prayer
      parent: Advice
    9107425a270f4a99b2791e40608eced2:
      title: The Benefits of Saving Lives
      parent: Advice
    f2d862bc2faa44adb24df339dd502100:
      title: Words of Advice
      parent: Advice
    b9f9f1a3ccec4bc79aa3004cd50a8c6e:
      title: 'The Rishi''s Maledictory Incantation: An Invocation of Wisdom Mind and
        Sacred Pledges for Reversing the Disturbances and Agitations of Dark Times
        In the Form of an Aspiration Prayer'
      parent: Aspiration Prayers
    cca5c809fb2f4a78bb5ea7cc550abed1:
      title: 'The Excellent Path of Supreme Great Bliss: A Prayer for Calling the
        Guru from Afar'
      parent: Calling the Guru from Afar
    c3a81bcdb8f946d18ed326889b7f3000:
      title: A Profound and Concise Guru Yoga
      parent: Guru Yoga
    312d70db4af24aaf80c7807df69ee6dd:
      title: Introduction to The Excellent Path of Devotion
      parent: Introductions
    43710af606fc42cfb495d4cf467a3e0b:
      title: Prayer for the Long Life of Namkhai Norbu Rinpoche
      parent: Long Life Prayers
    b32729486ed4447485054663141be7c2:
      title: Prayer for the Long Life of Soktsé Rinpoche
      parent: Long Life Prayers
    fd4f5dbe1d4444cb860a8ceed4608cd4:
      title: A Guide to Uḍḍiyāna (Ujjain), Benglor
      parent: Pilgrimage
    4425d390be424aaaa64a42c29bf1ba0e:
      title: 'Melodious Tambura of Delight: A Guide to Māratika Cave, Supreme Site
        of Immortality'
      parent: Pilgrimage
    4db9a345bce5425595859999d35bf948:
      title: Essence of All the Buddhas of Past, Present and Future
      parent: Prayers
    b9dbb1a289b846baaca8b9ea845ee916:
      title: 'The Condensed Essence: A Daily Practice of the Wrathful Guru Takhyung
        Barwa'
      parent: Sādhanas
    59e867dc7329486ba5c9793f496ffe99:
      title: The Ritual of the Bodhisattva Vow According to the Tradition of Patrul
        Rinpoche
      parent: Vows & Commitments
created_at: '2022-02-28T22:42:38.128688'
last_modified_at: '2022-02-28T22:42:38.128695'
